### ISSUE TITLE
Port to discord.py 2.0

### ISSUE THREAD

**Issue by lun-4** [slice/lifesaver#11]
I attempted to make the migration but failed miserably, instead I'm pinning to `1.7.3` in my bot. Maybe we should constrain the discord package version as `discord<2`?

**Comment by slice** [comment]
"Completed" with aecb8300b69566e56d233d1b398f2d5b28e59ca2, but I haven't done thorough testing. Please open any issues if you notice any regressions; I'm sure there's some lurking in a corner somewhere.
